Repository the-difference-engine/rescue-leftover-cuisine2, pull requests merged in 2019-10, with the labels that each got.

#359 Feature/346
  app/controllers/api/v1/comments_controller.rb
  app/controllers/api/v1/recipes_controller.rb
  app/models/comment.rb
  app/models/recipe.rb
  app/models/user.rb
  config/routes.rb
  db/migrate/20190926032521_create_comments.rb
  db/schema.rb
  db/seeds.rb
  frontend/src/components/RecipeComments/RecipeComments.css
  frontend/src/components/RecipeComments/RecipeComments.js
  frontend/src/containers/RecipePage/Recipe.js
  frontend/src/lib/apiClient.js
  test/fixtures/comments.yml
  test/models/comment_test.rb
Labels: CR: Needs Review

#364 Feature/342/recipe details2
  frontend/src/assets/bar-chart.png
  frontend/src/components/AuthItems/AuthItems.css
  frontend/src/components/EditRecipe/EditRecipeForm.css
  frontend/src/components/EditRecipe/EditRecipeForm.js
Labels: CR: Needs Review

#362 Feature/360/comment fix
  app/models/recipe.rb
  frontend/src/components/RecipeComments/RecipeComments.js
  frontend/src/containers/RecipePage/Recipe.js
Labels: CR: Approved

#367 Feature/343/tags search
  app/controllers/api/v1/recipes_controller.rb
  app/controllers/api/v1/tags_controller.rb
  app/models/recipe.rb
  app/models/tag.rb
  config/routes.rb
  db/migrate/20191009225254_create_join_table_recipes_tags.rb
  db/schema.rb
  db/seeds.rb
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/EditRecipe/EditRecipeForm.css
  frontend/src/components/EditRecipe/EditRecipeForm.js
  frontend/src/components/TagsBar/SingleTag/SingleTag.css
  frontend/src/components/TagsBar/SingleTag/SingleTag.js
  frontend/src/components/TagsBar/TagsBar.js
  frontend/src/containers/RecipePage/Recipe.js
  frontend/src/lib/apiClient.js
  test/controllers/api/v1/tags_controller_test.rb
Labels: CR: Changes Requested
