Repository the-difference-engine/rescue-leftover-cuisine2, pull requests merged in 2019-06, with the labels that each got.

#255 Feature/245/create acct name field update
  frontend/src/components/SignUp/SignUp.js
Labels: CR: Approved

#280 email validation regex added
  frontend/public/.maccheese.jpg.icloud
  frontend/src/components/SignUp/SignUp.js
Labels: CR: Approved

#260 Feature/165/profile page
  frontend/src/App.js
  frontend/src/assets/profilePic.PNG
  frontend/src/components/UserProfilePanels/SettingsTab.css
  frontend/src/components/UserProfilePanels/SettingsTab.js
  frontend/src/components/UserProfilePanels/UserInfo.css
  frontend/src/components/UserProfilePanels/UserInfo.js
  frontend/src/containers/ProfilePage/ProfilePage.css
  frontend/src/containers/ProfilePage/ProfilePage.js
Labels: CR: Approved

#287 Move package installation into build step
  Dockerfile
  README.md
  docker-compose.yml
Labels: CR: Needs Review

#252 Feature/243/unsuccesful login
  frontend/src/components/SignIn/SignIn.css
  frontend/src/components/SignIn/SignIn.js
Labels: CR: Questions

#253 Feature/247/passwordresetpage
  frontend/src/App.js
  frontend/src/components/NewPassword/NewPassword.css
  frontend/src/components/NewPassword/NewPassword.js
  frontend/src/containers/ResetPassword/ResetPasswordPage.css
  frontend/src/containers/ResetPassword/ResetPasswordPage.js
Labels: CR: Approved

#281 Feature/169
  frontend/src/components/MainSearch/MainSearch.css
  frontend/src/components/MainSearch/MainSearch.js
Labels: CR: Approved

#285 Feature/234/redirect
  frontend/src/components/MainSearch/MainSearch.js
  frontend/src/components/SearchBar/SearchBar.js
  frontend/src/components/SignIn/SignIn.js
  frontend/src/components/SignUp/SignUp.js
  frontend/src/containers/AdminPanel/AdminPanel.js
  frontend/src/containers/Homepage/Homepage.js
Labels: CR: Needs Review

#291 Added CSS for <a> to limit linking to the logo
  frontend/src/components/LogInPageHeader/LogInPageHeader.css
  frontend/src/components/LogInPageHeader/LogInPageHeader.js
Labels: CR: Approved

#297 Clear up some endpoint naming shenanigans
  app/controllers/api/v1/recipes_controller.rb
  app/controllers/api/v1/registrations_controller.rb
  app/controllers/application_controller.rb
  config/routes.rb
  frontend/src/lib/apiClient.js
  lib/custom_failure.rb
Labels: CR: Needs Review

#279 Feature/238
  frontend/src/App.js
  frontend/src/assets/bread.jpg
  frontend/src/containers/RecipePage/Recipe.css
  frontend/src/containers/RecipePage/Recipe.js
  frontend/src/containers/RecipePage/TagsBar/AddTag/AddTag.css
  frontend/src/containers/RecipePage/TagsBar/AddTag/AddTag.js
  frontend/src/containers/RecipePage/TagsBar/SingleTag/SingleTag.css
  frontend/src/containers/RecipePage/TagsBar/SingleTag/SingleTag.js
  frontend/src/containers/RecipePage/TagsBar/TagsBar.css
  frontend/src/containers/RecipePage/TagsBar/TagsBar.js
Labels: CR: Changes Requested, CR: Needs Review
