Repository the-difference-engine/rescue-leftover-cuisine2, pull requests merged in 2019-02, with the labels that each got.

#143 Homepage redux header
  docker-compose.yml
  frontend/src/assets/grilled-chicken1725.jpg
  frontend/src/assets/soup-kitchen.jpg
  frontend/src/components/BottomSignUp/BottomSignUp.css
  frontend/src/components/BottomSignUp/BottomSignUp.js
  frontend/src/components/Footer/Footer.js
  frontend/src/components/Header/Header.css
  frontend/src/components/Header/Header.js
  frontend/src/components/MainSearch/MainSearch.css
  frontend/src/components/MainSearch/MainSearch.js
  frontend/src/containers/Homepage/Homepage.css
  frontend/src/containers/Homepage/Homepage.js
  frontend/yarn.lock
Labels: CR: Changes Requested

#149 search text is now left; text shadow
  frontend/src/components/MainSearch/MainSearch.css
Labels: CR: Approved

#147 Banner
  frontend/public/index.html
  frontend/src/assets/grilled-chicken-dark.jpg
  frontend/src/components/BottomSignUp/BottomSignUp.css
  frontend/src/components/Header/Header.css
  frontend/src/components/Header/Header.js
  frontend/src/components/MainSearch/MainSearch.css
  frontend/src/containers/Homepage/Homepage.css
  frontend/src/index.css
Labels: CR: Approved

#145 Changed favicon and title
  frontend/public/favicon.ico
  frontend/public/index.html
Labels: CR: Approved

#161 Bug fix/seed issues
  db/seeds.rb
  frontend/public/recipe-seeds/roseappletart.jpg
  frontend/src/App.js
  frontend/src/components/SignUp/SignUp.css
  frontend/src/components/SignUp/SignUp.js
  frontend/src/components/sign_up/sign_up.js
Labels: CR: Needs Review
